name: Run Style Check
description: 'Runs a php style check based on symcons style'

runs:
  using: "composite"
  steps:
      - run: git submodule update --init -- .style
        shell: bash
      - run: wget https://cs.symfony.com/download/php-cs-fixer-v3.phar
        shell: bash
      - run: PHP_CS_FIXER_IGNORE_ENV=1  php php-cs-fixer-v3.phar fix --config=.style/.php-cs-fixer.php -v --dry-run --allow-risky=yes
        shell: bash
      - run: |
          if [[ -f ".style/json-check.php" ]]; then
            php .style/json-check.php fix .
          fi
        shell: bash
